services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: img_api
  #   container_name: micro_api_wsp
  #   restart: unless-stopped #Para resiliencia
  #   env_file:
  #     - .env
  #     - .env.development
  #   ports:
  #     - "${PORT:-4001}:4001"
  #   depends_on:
  #     mysql_dev:
  #       condition: service_healthy
  #   volumes:
  #     - ./src:/app/src
  #     - ./prisma:/app/prisma 
  #     # - ./wpp-sessions:/app/wpp-sessions
  #     - wpp_sessions_data:/app/wpp-sessions
  #     - /app/node_modules
  #   networks:
  #     - nestjs_network
  #   command: sh -c "npm run prisma:migrate && npm run start:dev" #Sobreescribir el comando de Dockerfile

  mysql_dev:
    image: mysql:8.0 
    container_name: mysql_dev
    restart: unless-stopped
    environment:
      # MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: wsp_messages
      # MYSQL_USER: apiuser
      # MYSQL_PASSWORD: apiPass123

      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_DATABASE:-wsp_messages}
      MYSQL_USER: ${DB_USERNAME:-nestjs}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}

    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d #Solo si el volumne no existe, para inicializar la DB
 
    networks:
      - nestjs_network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME:-nestjs}", "-p${DB_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_dev_data:
  wpp_sessions_data:

networks:
  nestjs_network:
