name: Deploy Micro Api Wsp (Docker Hub)

on:
  push:
    branches: [master]

jobs:
  build-and-push-img:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        run: |
          docker build -t yordii/micro-wsp-api:latest . -f Dockerfile.prod
          docker push yordii/micro-wsp-api:latest

  deploy-on-vps:
    runs-on: ubuntu-latest
    needs: build-and-push-img
    steps:
      - name: Pull & Run
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd micro_api_wsp/
            docker pull yordii/micro-wsp-api:latest
            docker-compose -f compose.prod.yml --env-file .env.production down
            docker-compose -f compose.prod.yml --env-file .env.production up -d
