name: Deploy Micro Api Wsp

on:
  push:
    branches: [master]

jobs:
  update-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4

      - name: Update compose.prod.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_KEY}}
          source: 'compose.prod.yml,mysql-init'
          target: '/home/ubuntu/micro_api_wsp/'
          overwrite: true

  push-img:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.setter.outputs.tag}}

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Create tag
        id: setter
        run: echo "tag=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push img
        run: |
          IMAGE_TAG=${{steps.setter.outputs.tag}}
          docker build -t yordii/micro-wsp-api:$IMAGE_TAG . -f Dockerfile.prod
          docker push yordii/micro-wsp-api:$IMAGE_TAG

  rm-containers:
    runs-on: ubuntu-latest
    needs: push-img
    steps:
      - name: Connect to VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker rm -f wsp_api_prod || true
            docker rm -f wsp_mysql_prod || true

  deploy:
    runs-on: ubuntu-latest
    needs: [rm-containers, push-img]
    steps:
      - name: Connect to VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            export IMAGE_TAG=${{needs.push-img.outputs.tag}}           

            cd micro_api_wsp/
            docker pull yordii/micro-wsp-api:$IMAGE_TAG           
            docker-compose -f compose.prod.yml --env-file .env.production up -d
