name: Deploy Micro Api Wsp (Docker Hub)

on:
  push:
    branches: [master]

jobs:
  push-dockerhub:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{steps.setter.outputs.tag}}

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Set image tag
        id: setter
        run: echo "tag=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        run: |
          IMAGE_TAG=${{steps.setter.outputs.tag}}
          docker build -t yordii/micro-wsp-api:$IMAGE_TAG . -f Dockerfile.prod
          docker push yordii/micro-wsp-api:$IMAGE_TAG

  rm-containers:
    runs-on: ubuntu-latest
    needs: push-dockerhub
    steps:
      - name: Down old version
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker rm -f wsp_api_prod || true
            docker rm -f wsp_mysql_prod || true

  deploy-on-vps:
    runs-on: ubuntu-latest
    needs: [rm-containers, push-dockerhub]
    steps:
      - name: Pull & Run
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd micro_api_wsp/
            export IMAGE_TAG=${{needs.push-dockerhub.outputs.image_tag}}           

            docker pull yordii/micro-wsp-api:$IMAGE_TAG

            #.env.production usa var IMAGE_TAG
            docker-compose -f compose.prod.yml --env-file .env.production up -d
